env: "combatv4"

env_args:
  scenario: "agent_vs_bot_example"
  key: "agent_vs_bot_example"
  time_limit: 200
  camp: "offensive"
  reward_type: "dense"


test_greedy: True
test_nepisode: 200
test_interval: 2000
log_interval: 2000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 2050000
