env: "combat"

env_args:
  key: "5s_50f"
  time_limit: 200
  map_size: [50, 50]
  n_ships: 5
  n_forts: 50
  param_share: True


test_greedy: True
test_nepisode: 200
test_interval: 2000
log_interval: 2000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 2050000
